// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.1
// source: dlq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DLQEnvelope wraps a single source record that a pipeline service gave up on.
// It preserves the source coordinates and the original payload byte-for-byte
// so a future replayer can re-inject the record.
type DLQEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          *DLQSource             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	OriginalPayload []byte                 `protobuf:"bytes,2,opt,name=original_payload,json=originalPayload,proto3" json:"original_payload,omitempty"`
	Stage           string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Attempts        int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	FailedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DLQEnvelope) Reset() {
	*x = DLQEnvelope{}
	mi := &file_dlq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQEnvelope) ProtoMessage() {}

func (x *DLQEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_dlq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQEnvelope.ProtoReflect.Descriptor instead.
func (*DLQEnvelope) Descriptor() ([]byte, []int) {
	return file_dlq_proto_rawDescGZIP(), []int{0}
}

func (x *DLQEnvelope) GetSource() *DLQSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DLQEnvelope) GetOriginalPayload() []byte {
	if x != nil {
		return x.OriginalPayload
	}
	return nil
}

func (x *DLQEnvelope) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DLQEnvelope) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DLQEnvelope) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DLQEnvelope) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

// DLQSource identifies where the failed record was read from.
type DLQSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DLQSource) Reset() {
	*x = DLQSource{}
	mi := &file_dlq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQSource) ProtoMessage() {}

func (x *DLQSource) ProtoReflect() protoreflect.Message {
	mi := &file_dlq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQSource.ProtoReflect.Descriptor instead.
func (*DLQSource) Descriptor() ([]byte, []int) {
	return file_dlq_proto_rawDescGZIP(), []int{1}
}

func (x *DLQSource) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DLQSource) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *DLQSource) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_dlq_proto protoreflect.FileDescriptor

const file_dlq_proto_rawDesc = "" +
	"\n" +
	"\tdlq.proto\x12\x03dlq\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\vDLQEnvelope\x12&\n" +
	"\x06source\x18\x01 \x01(\v2\x0e.dlq.DLQSourceR\x06source\x12)\n" +
	"\x10original_payload\x18\x02 \x01(\fR\x0foriginalPayload\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x127\n" +
	"\tfailed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\"W\n" +
	"\tDLQSource\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offsetB\bZ\x06pb/;pbb\x06proto3"

var (
	file_dlq_proto_rawDescOnce sync.Once
	file_dlq_proto_rawDescData []byte
)

func file_dlq_proto_rawDescGZIP() []byte {
	file_dlq_proto_rawDescOnce.Do(func() {
		file_dlq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dlq_proto_rawDesc), len(file_dlq_proto_rawDesc)))
	})
	return file_dlq_proto_rawDescData
}

var file_dlq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dlq_proto_goTypes = []any{
	(*DLQEnvelope)(nil),           // 0: dlq.DLQEnvelope
	(*DLQSource)(nil),             // 1: dlq.DLQSource
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_dlq_proto_depIdxs = []int32{
	1, // 0: dlq.DLQEnvelope.source:type_name -> dlq.DLQSource
	2, // 1: dlq.DLQEnvelope.failed_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dlq_proto_init() }
func file_dlq_proto_init() {
	if File_dlq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dlq_proto_rawDesc), len(file_dlq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dlq_proto_goTypes,
		DependencyIndexes: file_dlq_proto_depIdxs,
		MessageInfos:      file_dlq_proto_msgTypes,
	}.Build()
	File_dlq_proto = out.File
	file_dlq_proto_goTypes = nil
	file_dlq_proto_depIdxs = nil
}
