---
default_stages: [commit]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-case-conflict  # Check for files that would conflict in case-insensitive filesystems
          - id: check-merge-conflict  # Check for files that contain merge conflict strings.
          - id: forbid-new-submodules  # Check for git submodules
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: ['-s', '-c', './.yamllint', 'rules', 'logsources', 'values.yml', 'deprecated', 'lists']
    - repo: local
      hooks:
          - id: commit-msg-check
            name: Commit message checker
            description: This hook checks the commit message.
            entry: bash -c './scripts/commit-msg-checker.sh "$@" || true' --
            language: system
            stages: [commit-msg]
