title: CFC-Suspicious signin by AADC Sync account

id: 59d84cdf-2520-40d0-8cd7-70bf81e5f98c

status: stable

rule_version: 1

goal: |
    We look for Sign-in events by "Sync" Azure AD Accounts, with non-standard "App Display Name" attribute, to identify sign-ins that don't align with the characteristics of the known "Azure AD user account".


strategy_abstract_and_technical_context: |
    ## Hybrid environment?
    Most organizations use Active Directory to manage permissions and access to network resources. Many of these organizations are also starting to use Azure AD, a cloud-based identity and access management service, to manage user identities and access privileges to resources such as the Azure portal and Office 365.
    In hybrid identity implementations, objects are synchronized between the on-premises AD environments and Azure AD tenants. In such environments, users can use the same identity for both on-prem AD and Azure AD.

    ## Azure AD Connect?
    Azure AD Connect is a Microsoft application designed to achieve a hybrid identity by synchronizing on-prem AD objects with Azure AD objects.
    Azure AD Connect encompasses many features, the most important ones being password hash synchronization, pass-through authentication, federation integration (with ADFS), and synchronization (with Azure AD Connect Sync).
    In a hybrid identity implementation, integrity between on-prem environments and Azure AD tenants is important. To achieve this goal, Azure AD Connect matches user objects between Azure AD and AD.

    ## AD Sync account?

    As part of the express settings installation process, multiple accounts are created both in the on-premises (Windows Server Active Directory) and cloud (Azure AD) environments.
    The first account is the AD DS Connector Account. The account name is prefixed with `MSOL_` and it is created with a long complex password.
    This account's permissions are set based on features enabled during the service's installation, but in most common scenarios, the account has permissions to replicate directory changes, modify passwords, modify users, modify groups, and so on (see all the permissions here).
    In addition, during installation, an Azure AD account called the Azure AD Connector Account is also created. This account is used by the synchronization service to manage Azure AD objects. The account is created with a long complex password as well, and by default (if using the express settings) prefixed with `Sync_[ServerName]`.
    This user is assigned with the Directory Synchronization Accounts role (see detailed permissions of this role here). In older versions, this account might be assigned with the Global Administrator role.

    A threat actor may attempt to steal the Sync account credentials and use them to access Azure resources.
    We look for Sign-in events by "Sync" Azure AD Accounts, with non-standard "App Display Name" attribute, to identify sign-ins that don't align with the characteristics of the known "Azure AD user account".

references:
    - https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/whatis-azure-ad-connect
    - https://www.alitajran.com/sync-azure-ad-user/
    - https://www.microsoft.com/en-us/security/blog/2023/04/07/mercury-and-dev-1084-destructive-attack-on-hybrid-environment/

tags:
    - cloud
    - azure
    - identity
    - authentication
    - ks.coverage.publiccloud.azure
    - ks.coverage.identity
    - attack.T1078.004
    - attack.T1078.002
    - attack.T1550

date: '2023-06-19'

severity: high

requirements:

logsource:
    category: Directory
    product: Azure

investigation_steps:
    - Investigate activity of related Source IP
    - Look for suspicious events that occurred on the Azure AD Connect server prior to the sign-in activity.
    - Look for suspicious operations initiated by the Sync account after the suspicious sign-in activity.
    - Are you aware of this kind of activity conducted by organizational personnel using this user account?
    - |
      Are there any highly suspicious activities conducted by this user account, such as:
        * Update Service Principal
        * Add Service Principal Credentials
        * Add Owner to Service Principal
        * Add delegated permissions grant

falsepositives:
    - Unknown for now; none observed.

triggers:
    manual:
        - Azure Active Directory Connect is required in the environment.
        - |
          You can use the following commands to get the password of the `Sync` account:
          ```
            Install-Module AADInternals
            Import-Module AADInternals
            Get-AADIntSyncCredentials -AsBackgroundProcess $False

            Install-Module AzureAD
            Import-Module AzureAD

            # Connect to Azure as ADSync
            ## Get ADSyncConnect user and connect to AzureAD
            $adsyncuser = Get-AADIntSyncCredentials | Select -expand AADUser
            $adsyncpassword = Get-AADIntSyncCredentials | Select -expand AADUserPassword
            $adsyncuser_securepassword = ConvertTo-SecureString "$adsyncpassword" -AsPlainText -Force
            $adsyncuser_credential = New-Object System.Management.Automation.PSCredential($adsyncuser, $adsyncuser_securepassword)
            Get-AADIntAccessTokenForAADGraph -Credentials $adsyncuser_credential -savetocache
            Connect-AzureAD -Credential $adsyncuser_credential
          ```
        - |
          Connect to the sync account with the password that was retrived:
          ```
            az login --allow-no-subscriptions -u <sync account username> -p <sync account password>
          ```

observables:
    - field: username
      description: name of user
      aggregation: true
    - field: hostname
      description: name of host
      aggregation: false