// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: pkg/enrichments/rpc_enrichments/enrichment.proto

package rpc_enrichments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Enrichment_GetMetadata_FullMethodName = "/enrichments.Enrichment/GetMetadata"
	Enrichment_Init_FullMethodName        = "/enrichments.Enrichment/Init"
	Enrichment_Enrich_FullMethodName      = "/enrichments.Enrichment/Enrich"
	Enrichment_EnrichBatch_FullMethodName = "/enrichments.Enrichment/EnrichBatch"
	Enrichment_Shutdown_FullMethodName    = "/enrichments.Enrichment/Shutdown"
	Enrichment_Ping_FullMethodName        = "/enrichments.Enrichment/Ping"
)

// EnrichmentClient is the client API for Enrichment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrichmentClient interface {
	GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EnrichmentMetadata, error)
	Init(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Enrich(ctx context.Context, in *EnrichRequest, opts ...grpc.CallOption) (*EnrichResponse, error)
	EnrichBatch(ctx context.Context, in *EnrichBatchRequest, opts ...grpc.CallOption) (*EnrichBatchResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type enrichmentClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrichmentClient(cc grpc.ClientConnInterface) EnrichmentClient {
	return &enrichmentClient{cc}
}

func (c *enrichmentClient) GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EnrichmentMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichmentMetadata)
	err := c.cc.Invoke(ctx, Enrichment_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentClient) Init(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Enrichment_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentClient) Enrich(ctx context.Context, in *EnrichRequest, opts ...grpc.CallOption) (*EnrichResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichResponse)
	err := c.cc.Invoke(ctx, Enrichment_Enrich_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentClient) EnrichBatch(ctx context.Context, in *EnrichBatchRequest, opts ...grpc.CallOption) (*EnrichBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichBatchResponse)
	err := c.cc.Invoke(ctx, Enrichment_EnrichBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Enrichment_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Enrichment_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrichmentServer is the server API for Enrichment service.
// All implementations must embed UnimplementedEnrichmentServer
// for forward compatibility.
type EnrichmentServer interface {
	GetMetadata(context.Context, *Empty) (*EnrichmentMetadata, error)
	Init(context.Context, *Empty) (*Empty, error)
	Enrich(context.Context, *EnrichRequest) (*EnrichResponse, error)
	EnrichBatch(context.Context, *EnrichBatchRequest) (*EnrichBatchResponse, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedEnrichmentServer()
}

// UnimplementedEnrichmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrichmentServer struct{}

func (UnimplementedEnrichmentServer) GetMetadata(context.Context, *Empty) (*EnrichmentMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedEnrichmentServer) Init(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedEnrichmentServer) Enrich(context.Context, *EnrichRequest) (*EnrichResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enrich not implemented")
}
func (UnimplementedEnrichmentServer) EnrichBatch(context.Context, *EnrichBatchRequest) (*EnrichBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrichBatch not implemented")
}
func (UnimplementedEnrichmentServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedEnrichmentServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEnrichmentServer) mustEmbedUnimplementedEnrichmentServer() {}
func (UnimplementedEnrichmentServer) testEmbeddedByValue()                    {}

// UnsafeEnrichmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrichmentServer will
// result in compilation errors.
type UnsafeEnrichmentServer interface {
	mustEmbedUnimplementedEnrichmentServer()
}

func RegisterEnrichmentServer(s grpc.ServiceRegistrar, srv EnrichmentServer) {
	// If the following call pancis, it indicates UnimplementedEnrichmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Enrichment_ServiceDesc, srv)
}

func _Enrichment_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrichment_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServer).GetMetadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enrichment_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrichment_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServer).Init(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enrichment_Enrich_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServer).Enrich(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrichment_Enrich_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServer).Enrich(ctx, req.(*EnrichRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enrichment_EnrichBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServer).EnrichBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrichment_EnrichBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServer).EnrichBatch(ctx, req.(*EnrichBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enrichment_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrichment_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enrichment_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrichment_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Enrichment_ServiceDesc is the grpc.ServiceDesc for Enrichment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enrichment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enrichments.Enrichment",
	HandlerType: (*EnrichmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _Enrichment_GetMetadata_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _Enrichment_Init_Handler,
		},
		{
			MethodName: "Enrich",
			Handler:    _Enrichment_Enrich_Handler,
		},
		{
			MethodName: "EnrichBatch",
			Handler:    _Enrichment_EnrichBatch_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Enrichment_Shutdown_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Enrichment_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/enrichments/rpc_enrichments/enrichment.proto",
}
