// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.1
// source: pkg/enrichments/rpc_enrichments/enrichment.proto

package rpc_enrichments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnrichBatchRequest carries one encoded alerts.Alert per alert, not the Alert itself. A bytes
// field and a submessage field share proto's length-delimited encoding, so this is the same wire
// format the field had when it was declared as repeated alerts.Alert and either side of the
// handshake may predate the change. Bytes are what let the host encode each alert once for a batch
// and reuse it for every enrichment it is handed to, instead of once per call.
type EnrichBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        [][]byte               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichBatchRequest) Reset() {
	*x = EnrichBatchRequest{}
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichBatchRequest) ProtoMessage() {}

func (x *EnrichBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichBatchRequest.ProtoReflect.Descriptor instead.
func (*EnrichBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichBatchRequest) GetAlerts() [][]byte {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type EnrichItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichItem) Reset() {
	*x = EnrichItem{}
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichItem) ProtoMessage() {}

func (x *EnrichItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichItem.ProtoReflect.Descriptor instead.
func (*EnrichItem) Descriptor() ([]byte, []int) {
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichItem) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *EnrichItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnrichBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EnrichItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichBatchResponse) Reset() {
	*x = EnrichBatchResponse{}
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichBatchResponse) ProtoMessage() {}

func (x *EnrichBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichBatchResponse.ProtoReflect.Descriptor instead.
func (*EnrichBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichBatchResponse) GetItems() []*EnrichItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pkg_enrichments_rpc_enrichments_enrichment_proto protoreflect.FileDescriptor

const file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc = "" +
	"\n" +
	"0pkg/enrichments/rpc_enrichments/enrichment.proto\x12\venrichments\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x12EnrichBatchRequest\x12\x16\n" +
	"\x06alerts\x18\x01 \x03(\fR\x06alerts\"C\n" +
	"\n" +
	"EnrichItem\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"D\n" +
	"\x13EnrichBatchResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.enrichments.EnrichItemR\x05items2\x8a\x02\n" +
	"\n" +
	"Enrichment\x12P\n" +
	"\vEnrichBatch\x12\x1f.enrichments.EnrichBatchRequest\x1a .enrichments.EnrichBatchResponse\x126\n" +
	"\x04Init\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\"Z rpc_enrichments/;rpc_enrichmentsb\x06proto3"

var (
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescOnce sync.Once
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescData []byte
)

func file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP() []byte {
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescOnce.Do(func() {
		file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc), len(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc)))
	})
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescData
}

var file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_enrichments_rpc_enrichments_enrichment_proto_goTypes = []any{
	(*EnrichBatchRequest)(nil),  // 0: enrichments.EnrichBatchRequest
	(*EnrichItem)(nil),          // 1: enrichments.EnrichItem
	(*EnrichBatchResponse)(nil), // 2: enrichments.EnrichBatchResponse
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_pkg_enrichments_rpc_enrichments_enrichment_proto_depIdxs = []int32{
	1, // 0: enrichments.EnrichBatchResponse.items:type_name -> enrichments.EnrichItem
	0, // 1: enrichments.Enrichment.EnrichBatch:input_type -> enrichments.EnrichBatchRequest
	3, // 2: enrichments.Enrichment.Init:input_type -> google.protobuf.Empty
	3, // 3: enrichments.Enrichment.Shutdown:input_type -> google.protobuf.Empty
	3, // 4: enrichments.Enrichment.Ping:input_type -> google.protobuf.Empty
	2, // 5: enrichments.Enrichment.EnrichBatch:output_type -> enrichments.EnrichBatchResponse
	3, // 6: enrichments.Enrichment.Init:output_type -> google.protobuf.Empty
	3, // 7: enrichments.Enrichment.Shutdown:output_type -> google.protobuf.Empty
	3, // 8: enrichments.Enrichment.Ping:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_enrichments_rpc_enrichments_enrichment_proto_init() }
func file_pkg_enrichments_rpc_enrichments_enrichment_proto_init() {
	if File_pkg_enrichments_rpc_enrichments_enrichment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc), len(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_enrichments_rpc_enrichments_enrichment_proto_goTypes,
		DependencyIndexes: file_pkg_enrichments_rpc_enrichments_enrichment_proto_depIdxs,
		MessageInfos:      file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes,
	}.Build()
	File_pkg_enrichments_rpc_enrichments_enrichment_proto = out.File
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_goTypes = nil
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_depIdxs = nil
}
