// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: pkg/enrichments/rpc_enrichments/enrichment.proto

package rpc_enrichments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP(), []int{0}
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type EnrichBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichBatchRequest) Reset() {
	*x = EnrichBatchRequest{}
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichBatchRequest) ProtoMessage() {}

func (x *EnrichBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichBatchRequest.ProtoReflect.Descriptor instead.
func (*EnrichBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichBatchRequest) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type EnrichBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichBatchResponse) Reset() {
	*x = EnrichBatchResponse{}
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichBatchResponse) ProtoMessage() {}

func (x *EnrichBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichBatchResponse.ProtoReflect.Descriptor instead.
func (*EnrichBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP(), []int{3}
}

func (x *EnrichBatchResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_pkg_enrichments_rpc_enrichments_enrichment_proto protoreflect.FileDescriptor

const file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc = "" +
	"\n" +
	"0pkg/enrichments/rpc_enrichments/enrichment.proto\x12\venrichments\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\x05Alert\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"@\n" +
	"\x12EnrichBatchRequest\x12*\n" +
	"\x06alerts\x18\x01 \x03(\v2\x12.enrichments.AlertR\x06alerts\"A\n" +
	"\x13EnrichBatchResponse\x12*\n" +
	"\x06alerts\x18\x01 \x03(\v2\x12.enrichments.AlertR\x06alerts2\xf2\x01\n" +
	"\n" +
	"Enrichment\x12.\n" +
	"\x04Init\x12\x12.enrichments.Empty\x1a\x12.enrichments.Empty\x12P\n" +
	"\vEnrichBatch\x12\x1f.enrichments.EnrichBatchRequest\x1a .enrichments.EnrichBatchResponse\x122\n" +
	"\bShutdown\x12\x12.enrichments.Empty\x1a\x12.enrichments.Empty\x12.\n" +
	"\x04Ping\x12\x12.enrichments.Empty\x1a\x12.enrichments.EmptyB\"Z rpc_enrichments/;rpc_enrichmentsb\x06proto3"

var (
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescOnce sync.Once
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescData []byte
)

func file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescGZIP() []byte {
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescOnce.Do(func() {
		file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc), len(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc)))
	})
	return file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDescData
}

var file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_enrichments_rpc_enrichments_enrichment_proto_goTypes = []any{
	(*Empty)(nil),               // 0: enrichments.Empty
	(*Alert)(nil),               // 1: enrichments.Alert
	(*EnrichBatchRequest)(nil),  // 2: enrichments.EnrichBatchRequest
	(*EnrichBatchResponse)(nil), // 3: enrichments.EnrichBatchResponse
}
var file_pkg_enrichments_rpc_enrichments_enrichment_proto_depIdxs = []int32{
	1, // 0: enrichments.EnrichBatchRequest.alerts:type_name -> enrichments.Alert
	1, // 1: enrichments.EnrichBatchResponse.alerts:type_name -> enrichments.Alert
	0, // 2: enrichments.Enrichment.Init:input_type -> enrichments.Empty
	2, // 3: enrichments.Enrichment.EnrichBatch:input_type -> enrichments.EnrichBatchRequest
	0, // 4: enrichments.Enrichment.Shutdown:input_type -> enrichments.Empty
	0, // 5: enrichments.Enrichment.Ping:input_type -> enrichments.Empty
	0, // 6: enrichments.Enrichment.Init:output_type -> enrichments.Empty
	3, // 7: enrichments.Enrichment.EnrichBatch:output_type -> enrichments.EnrichBatchResponse
	0, // 8: enrichments.Enrichment.Shutdown:output_type -> enrichments.Empty
	0, // 9: enrichments.Enrichment.Ping:output_type -> enrichments.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_enrichments_rpc_enrichments_enrichment_proto_init() }
func file_pkg_enrichments_rpc_enrichments_enrichment_proto_init() {
	if File_pkg_enrichments_rpc_enrichments_enrichment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc), len(file_pkg_enrichments_rpc_enrichments_enrichment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_enrichments_rpc_enrichments_enrichment_proto_goTypes,
		DependencyIndexes: file_pkg_enrichments_rpc_enrichments_enrichment_proto_depIdxs,
		MessageInfos:      file_pkg_enrichments_rpc_enrichments_enrichment_proto_msgTypes,
	}.Build()
	File_pkg_enrichments_rpc_enrichments_enrichment_proto = out.File
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_goTypes = nil
	file_pkg_enrichments_rpc_enrichments_enrichment_proto_depIdxs = nil
}
