// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: enrichment.proto

package rpc_enrichments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_enrichment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_enrichment_proto_rawDescGZIP(), []int{0}
}

type EnrichmentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DependsOn     []string               `protobuf:"bytes,5,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichmentMetadata) Reset() {
	*x = EnrichmentMetadata{}
	mi := &file_enrichment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentMetadata) ProtoMessage() {}

func (x *EnrichmentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentMetadata.ProtoReflect.Descriptor instead.
func (*EnrichmentMetadata) Descriptor() ([]byte, []int) {
	return file_enrichment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichmentMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnrichmentMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrichmentMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EnrichmentMetadata) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EnrichmentMetadata) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *EnrichmentMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_enrichment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_enrichment_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type EnrichRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichRequest) Reset() {
	*x = EnrichRequest{}
	mi := &file_enrichment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichRequest) ProtoMessage() {}

func (x *EnrichRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichRequest.ProtoReflect.Descriptor instead.
func (*EnrichRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_proto_rawDescGZIP(), []int{3}
}

func (x *EnrichRequest) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type EnrichResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichResponse) Reset() {
	*x = EnrichResponse{}
	mi := &file_enrichment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichResponse) ProtoMessage() {}

func (x *EnrichResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichResponse.ProtoReflect.Descriptor instead.
func (*EnrichResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_proto_rawDescGZIP(), []int{4}
}

func (x *EnrichResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

var File_enrichment_proto protoreflect.FileDescriptor

const file_enrichment_proto_rawDesc = "" +
	"\n" +
	"\x10enrichment.proto\x12\venrichments\"\a\n" +
	"\x05Empty\"\xad\x01\n" +
	"\x12EnrichmentMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x05 \x03(\tR\tdependsOn\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\x1b\n" +
	"\x05Alert\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"9\n" +
	"\rEnrichRequest\x12(\n" +
	"\x05alert\x18\x01 \x01(\v2\x12.enrichments.AlertR\x05alert\":\n" +
	"\x0eEnrichResponse\x12(\n" +
	"\x05alert\x18\x01 \x01(\v2\x12.enrichments.AlertR\x05alert2\xa7\x02\n" +
	"\n" +
	"Enrichment\x12B\n" +
	"\vGetMetadata\x12\x12.enrichments.Empty\x1a\x1f.enrichments.EnrichmentMetadata\x12.\n" +
	"\x04Init\x12\x12.enrichments.Empty\x1a\x12.enrichments.Empty\x12A\n" +
	"\x06Enrich\x12\x1a.enrichments.EnrichRequest\x1a\x1b.enrichments.EnrichResponse\x122\n" +
	"\bShutdown\x12\x12.enrichments.Empty\x1a\x12.enrichments.Empty\x12.\n" +
	"\x04Ping\x12\x12.enrichments.Empty\x1a\x12.enrichments.EmptyB\"Z rpc_enrichments/;rpc_enrichmentsb\x06proto3"

var (
	file_enrichment_proto_rawDescOnce sync.Once
	file_enrichment_proto_rawDescData []byte
)

func file_enrichment_proto_rawDescGZIP() []byte {
	file_enrichment_proto_rawDescOnce.Do(func() {
		file_enrichment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrichment_proto_rawDesc), len(file_enrichment_proto_rawDesc)))
	})
	return file_enrichment_proto_rawDescData
}

var file_enrichment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_enrichment_proto_goTypes = []any{
	(*Empty)(nil),              // 0: enrichments.Empty
	(*EnrichmentMetadata)(nil), // 1: enrichments.EnrichmentMetadata
	(*Alert)(nil),              // 2: enrichments.Alert
	(*EnrichRequest)(nil),      // 3: enrichments.EnrichRequest
	(*EnrichResponse)(nil),     // 4: enrichments.EnrichResponse
}
var file_enrichment_proto_depIdxs = []int32{
	2, // 0: enrichments.EnrichRequest.alert:type_name -> enrichments.Alert
	2, // 1: enrichments.EnrichResponse.alert:type_name -> enrichments.Alert
	0, // 2: enrichments.Enrichment.GetMetadata:input_type -> enrichments.Empty
	0, // 3: enrichments.Enrichment.Init:input_type -> enrichments.Empty
	3, // 4: enrichments.Enrichment.Enrich:input_type -> enrichments.EnrichRequest
	0, // 5: enrichments.Enrichment.Shutdown:input_type -> enrichments.Empty
	0, // 6: enrichments.Enrichment.Ping:input_type -> enrichments.Empty
	1, // 7: enrichments.Enrichment.GetMetadata:output_type -> enrichments.EnrichmentMetadata
	0, // 8: enrichments.Enrichment.Init:output_type -> enrichments.Empty
	4, // 9: enrichments.Enrichment.Enrich:output_type -> enrichments.EnrichResponse
	0, // 10: enrichments.Enrichment.Shutdown:output_type -> enrichments.Empty
	0, // 11: enrichments.Enrichment.Ping:output_type -> enrichments.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_enrichment_proto_init() }
func file_enrichment_proto_init() {
	if File_enrichment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrichment_proto_rawDesc), len(file_enrichment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enrichment_proto_goTypes,
		DependencyIndexes: file_enrichment_proto_depIdxs,
		MessageInfos:      file_enrichment_proto_msgTypes,
	}.Build()
	File_enrichment_proto = out.File
	file_enrichment_proto_goTypes = nil
	file_enrichment_proto_depIdxs = nil
}
