// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.1
// source: pkg/matchers/rpc_matchers/matcher.proto

package rpc_matchers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MatchBatchRequest carries one encoded google.protobuf.Struct per event, not the Struct itself. A
// bytes field and a submessage field share proto's length-delimited encoding, so this is the same
// wire format the field had when it was declared as repeated google.protobuf.Struct and either side
// of the handshake may predate the change. Bytes are what let the host encode each event once for a
// batch and reuse it for every matcher that evaluates the batch, instead of once per matcher.
type MatchBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        [][]byte               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchBatchRequest) Reset() {
	*x = MatchBatchRequest{}
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchBatchRequest) ProtoMessage() {}

func (x *MatchBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchBatchRequest.ProtoReflect.Descriptor instead.
func (*MatchBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP(), []int{0}
}

func (x *MatchBatchRequest) GetEvents() [][]byte {
	if x != nil {
		return x.Events
	}
	return nil
}

type MatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchItem) Reset() {
	*x = MatchItem{}
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchItem) ProtoMessage() {}

func (x *MatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchItem.ProtoReflect.Descriptor instead.
func (*MatchItem) Descriptor() ([]byte, []int) {
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP(), []int{1}
}

func (x *MatchItem) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *MatchItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MatchBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MatchItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchBatchResponse) Reset() {
	*x = MatchBatchResponse{}
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchBatchResponse) ProtoMessage() {}

func (x *MatchBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchBatchResponse.ProtoReflect.Descriptor instead.
func (*MatchBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP(), []int{2}
}

func (x *MatchBatchResponse) GetItems() []*MatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pkg_matchers_rpc_matchers_matcher_proto protoreflect.FileDescriptor

const file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc = "" +
	"\n" +
	"'pkg/matchers/rpc_matchers/matcher.proto\x12\bmatchers\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x11MatchBatchRequest\x12\x16\n" +
	"\x06events\x18\x01 \x03(\fR\x06events\";\n" +
	"\tMatchItem\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x12MatchBatchResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.matchers.MatchItemR\x05items2\xfe\x01\n" +
	"\aMatcher\x12G\n" +
	"\n" +
	"MatchBatch\x12\x1b.matchers.MatchBatchRequest\x1a\x1c.matchers.MatchBatchResponse\x126\n" +
	"\x04Init\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x1cZ\x1arpc_matchers/;rpc_matchersb\x06proto3"

var (
	file_pkg_matchers_rpc_matchers_matcher_proto_rawDescOnce sync.Once
	file_pkg_matchers_rpc_matchers_matcher_proto_rawDescData []byte
)

func file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP() []byte {
	file_pkg_matchers_rpc_matchers_matcher_proto_rawDescOnce.Do(func() {
		file_pkg_matchers_rpc_matchers_matcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc), len(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc)))
	})
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescData
}

var file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_matchers_rpc_matchers_matcher_proto_goTypes = []any{
	(*MatchBatchRequest)(nil),  // 0: matchers.MatchBatchRequest
	(*MatchItem)(nil),          // 1: matchers.MatchItem
	(*MatchBatchResponse)(nil), // 2: matchers.MatchBatchResponse
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_pkg_matchers_rpc_matchers_matcher_proto_depIdxs = []int32{
	1, // 0: matchers.MatchBatchResponse.items:type_name -> matchers.MatchItem
	0, // 1: matchers.Matcher.MatchBatch:input_type -> matchers.MatchBatchRequest
	3, // 2: matchers.Matcher.Init:input_type -> google.protobuf.Empty
	3, // 3: matchers.Matcher.Shutdown:input_type -> google.protobuf.Empty
	3, // 4: matchers.Matcher.Ping:input_type -> google.protobuf.Empty
	2, // 5: matchers.Matcher.MatchBatch:output_type -> matchers.MatchBatchResponse
	3, // 6: matchers.Matcher.Init:output_type -> google.protobuf.Empty
	3, // 7: matchers.Matcher.Shutdown:output_type -> google.protobuf.Empty
	3, // 8: matchers.Matcher.Ping:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_matchers_rpc_matchers_matcher_proto_init() }
func file_pkg_matchers_rpc_matchers_matcher_proto_init() {
	if File_pkg_matchers_rpc_matchers_matcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc), len(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_matchers_rpc_matchers_matcher_proto_goTypes,
		DependencyIndexes: file_pkg_matchers_rpc_matchers_matcher_proto_depIdxs,
		MessageInfos:      file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes,
	}.Build()
	File_pkg_matchers_rpc_matchers_matcher_proto = out.File
	file_pkg_matchers_rpc_matchers_matcher_proto_goTypes = nil
	file_pkg_matchers_rpc_matchers_matcher_proto_depIdxs = nil
}
