// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: matcher.proto

package rpc_matchers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_matcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_matcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_matcher_proto_rawDescGZIP(), []int{0}
}

type MatcherMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Global        bool                   `protobuf:"varint,5,opt,name=global,proto3" json:"global,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatcherMetadata) Reset() {
	*x = MatcherMetadata{}
	mi := &file_matcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatcherMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatcherMetadata) ProtoMessage() {}

func (x *MatcherMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_matcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatcherMetadata.ProtoReflect.Descriptor instead.
func (*MatcherMetadata) Descriptor() ([]byte, []int) {
	return file_matcher_proto_rawDescGZIP(), []int{1}
}

func (x *MatcherMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MatcherMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MatcherMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MatcherMetadata) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MatcherMetadata) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

func (x *MatcherMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_matcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_matcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_matcher_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_matcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_matcher_proto_rawDescGZIP(), []int{3}
}

func (x *MatchRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_matcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_matcher_proto_rawDescGZIP(), []int{4}
}

func (x *MatchResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

var File_matcher_proto protoreflect.FileDescriptor

const file_matcher_proto_rawDesc = "" +
	"\n" +
	"\rmatcher.proto\x12\bmatchers\"\a\n" +
	"\x05Empty\"\xa3\x01\n" +
	"\x0fMatcherMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x16\n" +
	"\x06global\x18\x05 \x01(\bR\x06global\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\x1b\n" +
	"\x05Event\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"5\n" +
	"\fMatchRequest\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.matchers.EventR\x05event\")\n" +
	"\rMatchResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched2\x80\x02\n" +
	"\aMatcher\x129\n" +
	"\vGetMetadata\x12\x0f.matchers.Empty\x1a\x19.matchers.MatcherMetadata\x12(\n" +
	"\x04Init\x12\x0f.matchers.Empty\x1a\x0f.matchers.Empty\x128\n" +
	"\x05Match\x12\x16.matchers.MatchRequest\x1a\x17.matchers.MatchResponse\x12,\n" +
	"\bShutdown\x12\x0f.matchers.Empty\x1a\x0f.matchers.Empty\x12(\n" +
	"\x04Ping\x12\x0f.matchers.Empty\x1a\x0f.matchers.EmptyB\x1cZ\x1arpc_matchers/;rpc_matchersb\x06proto3"

var (
	file_matcher_proto_rawDescOnce sync.Once
	file_matcher_proto_rawDescData []byte
)

func file_matcher_proto_rawDescGZIP() []byte {
	file_matcher_proto_rawDescOnce.Do(func() {
		file_matcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matcher_proto_rawDesc), len(file_matcher_proto_rawDesc)))
	})
	return file_matcher_proto_rawDescData
}

var file_matcher_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_matcher_proto_goTypes = []any{
	(*Empty)(nil),           // 0: matchers.Empty
	(*MatcherMetadata)(nil), // 1: matchers.MatcherMetadata
	(*Event)(nil),           // 2: matchers.Event
	(*MatchRequest)(nil),    // 3: matchers.MatchRequest
	(*MatchResponse)(nil),   // 4: matchers.MatchResponse
}
var file_matcher_proto_depIdxs = []int32{
	2, // 0: matchers.MatchRequest.event:type_name -> matchers.Event
	0, // 1: matchers.Matcher.GetMetadata:input_type -> matchers.Empty
	0, // 2: matchers.Matcher.Init:input_type -> matchers.Empty
	3, // 3: matchers.Matcher.Match:input_type -> matchers.MatchRequest
	0, // 4: matchers.Matcher.Shutdown:input_type -> matchers.Empty
	0, // 5: matchers.Matcher.Ping:input_type -> matchers.Empty
	1, // 6: matchers.Matcher.GetMetadata:output_type -> matchers.MatcherMetadata
	0, // 7: matchers.Matcher.Init:output_type -> matchers.Empty
	4, // 8: matchers.Matcher.Match:output_type -> matchers.MatchResponse
	0, // 9: matchers.Matcher.Shutdown:output_type -> matchers.Empty
	0, // 10: matchers.Matcher.Ping:output_type -> matchers.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_matcher_proto_init() }
func file_matcher_proto_init() {
	if File_matcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matcher_proto_rawDesc), len(file_matcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matcher_proto_goTypes,
		DependencyIndexes: file_matcher_proto_depIdxs,
		MessageInfos:      file_matcher_proto_msgTypes,
	}.Build()
	File_matcher_proto = out.File
	file_matcher_proto_goTypes = nil
	file_matcher_proto_depIdxs = nil
}
