syntax = "proto3";
package matchers;
option go_package = "rpc_matchers/;rpc_matchers";

import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";

message MatchBatchRequest  { repeated google.protobuf.Struct events = 1; }

message MatchItem {
  bool matched = 1;
  string error = 2;
}

message MatchBatchResponse {
  repeated MatchItem items = 1;
}

service Matcher {
  rpc MatchBatch(MatchBatchRequest)   returns (MatchBatchResponse);
  rpc Init(google.protobuf.Empty)     returns (google.protobuf.Empty);
  rpc Shutdown(google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc Ping(google.protobuf.Empty)     returns (google.protobuf.Empty);
}
