syntax = "proto3";
package matchers;
option go_package = "rpc_matchers/;rpc_matchers";

import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";

message MatchBatchRequest  { repeated google.protobuf.Struct events = 1; }

message MatchBatchResponse {
  repeated bool results = 1;
  repeated string errors = 2;
}

service Matcher {
  rpc MatchBatch(MatchBatchRequest)   returns (MatchBatchResponse);
  rpc Init(google.protobuf.Empty)     returns (google.protobuf.Empty);
  rpc Shutdown(google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc Ping(google.protobuf.Empty)     returns (google.protobuf.Empty);
}
