// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: pkg/matchers/rpc_matchers/matcher.proto

package rpc_matchers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type MatchBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchBatchRequest) Reset() {
	*x = MatchBatchRequest{}
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchBatchRequest) ProtoMessage() {}

func (x *MatchBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchBatchRequest.ProtoReflect.Descriptor instead.
func (*MatchBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP(), []int{2}
}

func (x *MatchBatchRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type MatchBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       []bool                 `protobuf:"varint,1,rep,packed,name=matched,proto3" json:"matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchBatchResponse) Reset() {
	*x = MatchBatchResponse{}
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchBatchResponse) ProtoMessage() {}

func (x *MatchBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchBatchResponse.ProtoReflect.Descriptor instead.
func (*MatchBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP(), []int{3}
}

func (x *MatchBatchResponse) GetMatched() []bool {
	if x != nil {
		return x.Matched
	}
	return nil
}

var File_pkg_matchers_rpc_matchers_matcher_proto protoreflect.FileDescriptor

const file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc = "" +
	"\n" +
	"'pkg/matchers/rpc_matchers/matcher.proto\x12\bmatchers\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\x05Event\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"<\n" +
	"\x11MatchBatchRequest\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.matchers.EventR\x06events\".\n" +
	"\x12MatchBatchResponse\x12\x18\n" +
	"\amatched\x18\x01 \x03(\bR\amatched2\xd4\x01\n" +
	"\aMatcher\x12(\n" +
	"\x04Init\x12\x0f.matchers.Empty\x1a\x0f.matchers.Empty\x12G\n" +
	"\n" +
	"MatchBatch\x12\x1b.matchers.MatchBatchRequest\x1a\x1c.matchers.MatchBatchResponse\x12,\n" +
	"\bShutdown\x12\x0f.matchers.Empty\x1a\x0f.matchers.Empty\x12(\n" +
	"\x04Ping\x12\x0f.matchers.Empty\x1a\x0f.matchers.EmptyB\x1cZ\x1arpc_matchers/;rpc_matchersb\x06proto3"

var (
	file_pkg_matchers_rpc_matchers_matcher_proto_rawDescOnce sync.Once
	file_pkg_matchers_rpc_matchers_matcher_proto_rawDescData []byte
)

func file_pkg_matchers_rpc_matchers_matcher_proto_rawDescGZIP() []byte {
	file_pkg_matchers_rpc_matchers_matcher_proto_rawDescOnce.Do(func() {
		file_pkg_matchers_rpc_matchers_matcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc), len(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc)))
	})
	return file_pkg_matchers_rpc_matchers_matcher_proto_rawDescData
}

var file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_matchers_rpc_matchers_matcher_proto_goTypes = []any{
	(*Empty)(nil),              // 0: matchers.Empty
	(*Event)(nil),              // 1: matchers.Event
	(*MatchBatchRequest)(nil),  // 2: matchers.MatchBatchRequest
	(*MatchBatchResponse)(nil), // 3: matchers.MatchBatchResponse
}
var file_pkg_matchers_rpc_matchers_matcher_proto_depIdxs = []int32{
	1, // 0: matchers.MatchBatchRequest.events:type_name -> matchers.Event
	0, // 1: matchers.Matcher.Init:input_type -> matchers.Empty
	2, // 2: matchers.Matcher.MatchBatch:input_type -> matchers.MatchBatchRequest
	0, // 3: matchers.Matcher.Shutdown:input_type -> matchers.Empty
	0, // 4: matchers.Matcher.Ping:input_type -> matchers.Empty
	0, // 5: matchers.Matcher.Init:output_type -> matchers.Empty
	3, // 6: matchers.Matcher.MatchBatch:output_type -> matchers.MatchBatchResponse
	0, // 7: matchers.Matcher.Shutdown:output_type -> matchers.Empty
	0, // 8: matchers.Matcher.Ping:output_type -> matchers.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_matchers_rpc_matchers_matcher_proto_init() }
func file_pkg_matchers_rpc_matchers_matcher_proto_init() {
	if File_pkg_matchers_rpc_matchers_matcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc), len(file_pkg_matchers_rpc_matchers_matcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_matchers_rpc_matchers_matcher_proto_goTypes,
		DependencyIndexes: file_pkg_matchers_rpc_matchers_matcher_proto_depIdxs,
		MessageInfos:      file_pkg_matchers_rpc_matchers_matcher_proto_msgTypes,
	}.Build()
	File_pkg_matchers_rpc_matchers_matcher_proto = out.File
	file_pkg_matchers_rpc_matchers_matcher_proto_goTypes = nil
	file_pkg_matchers_rpc_matchers_matcher_proto_depIdxs = nil
}
