syntax = "proto3";
package formatters;
option go_package = "rpc_formatters/;rpc_formatters";

import "google/protobuf/empty.proto";
import "pkg/alerts/pb/alert.proto";

message FormatBatchRequest  { repeated alerts.Alert alerts = 1; } // structured alerts.Alert per alert

message FormatItem {
  bytes result_json = 1;
  string error = 2;
}

message FormatBatchResponse {
  repeated FormatItem items = 1;
}

service Formatter {
  rpc FormatBatch(FormatBatchRequest) returns (FormatBatchResponse);
  rpc Init(google.protobuf.Empty)     returns (google.protobuf.Empty);
  rpc Shutdown(google.protobuf.Empty) returns (google.protobuf.Empty);
  rpc Ping(google.protobuf.Empty)     returns (google.protobuf.Empty);
}
