// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: pkg/formatters/rpc_formatters/formatter.proto

package rpc_formatters

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Formatter_Init_FullMethodName        = "/formatters.Formatter/Init"
	Formatter_FormatBatch_FullMethodName = "/formatters.Formatter/FormatBatch"
	Formatter_Shutdown_FullMethodName    = "/formatters.Formatter/Shutdown"
	Formatter_Ping_FullMethodName        = "/formatters.Formatter/Ping"
)

// FormatterClient is the client API for Formatter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormatterClient interface {
	Init(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	FormatBatch(ctx context.Context, in *FormatBatchRequest, opts ...grpc.CallOption) (*FormatBatchResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type formatterClient struct {
	cc grpc.ClientConnInterface
}

func NewFormatterClient(cc grpc.ClientConnInterface) FormatterClient {
	return &formatterClient{cc}
}

func (c *formatterClient) Init(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Formatter_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatterClient) FormatBatch(ctx context.Context, in *FormatBatchRequest, opts ...grpc.CallOption) (*FormatBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FormatBatchResponse)
	err := c.cc.Invoke(ctx, Formatter_FormatBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatterClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Formatter_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatterClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Formatter_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormatterServer is the server API for Formatter service.
// All implementations must embed UnimplementedFormatterServer
// for forward compatibility.
type FormatterServer interface {
	Init(context.Context, *Empty) (*Empty, error)
	FormatBatch(context.Context, *FormatBatchRequest) (*FormatBatchResponse, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedFormatterServer()
}

// UnimplementedFormatterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFormatterServer struct{}

func (UnimplementedFormatterServer) Init(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedFormatterServer) FormatBatch(context.Context, *FormatBatchRequest) (*FormatBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FormatBatch not implemented")
}
func (UnimplementedFormatterServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedFormatterServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFormatterServer) mustEmbedUnimplementedFormatterServer() {}
func (UnimplementedFormatterServer) testEmbeddedByValue()                   {}

// UnsafeFormatterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormatterServer will
// result in compilation errors.
type UnsafeFormatterServer interface {
	mustEmbedUnimplementedFormatterServer()
}

func RegisterFormatterServer(s grpc.ServiceRegistrar, srv FormatterServer) {
	// If the following call pancis, it indicates UnimplementedFormatterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Formatter_ServiceDesc, srv)
}

func _Formatter_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatterServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Formatter_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatterServer).Init(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Formatter_FormatBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormatBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatterServer).FormatBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Formatter_FormatBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatterServer).FormatBatch(ctx, req.(*FormatBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Formatter_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatterServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Formatter_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatterServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Formatter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Formatter_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatterServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Formatter_ServiceDesc is the grpc.ServiceDesc for Formatter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Formatter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "formatters.Formatter",
	HandlerType: (*FormatterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Formatter_Init_Handler,
		},
		{
			MethodName: "FormatBatch",
			Handler:    _Formatter_FormatBatch_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Formatter_Shutdown_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Formatter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/formatters/rpc_formatters/formatter.proto",
}
