// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.1
// source: pkg/formatters/rpc_formatters/formatter.proto

package rpc_formatters

import (
	pb "github.com/harishhary/blink/pkg/alerts/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FormatBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*pb.Alert            `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatBatchRequest) Reset() {
	*x = FormatBatchRequest{}
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatBatchRequest) ProtoMessage() {}

func (x *FormatBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatBatchRequest.ProtoReflect.Descriptor instead.
func (*FormatBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_formatters_rpc_formatters_formatter_proto_rawDescGZIP(), []int{0}
}

func (x *FormatBatchRequest) GetAlerts() []*pb.Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type FormatBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    [][]byte               `protobuf:"bytes,1,rep,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // one JSON-encoded map[string]any per alert
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`                           // one item error string per alert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatBatchResponse) Reset() {
	*x = FormatBatchResponse{}
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatBatchResponse) ProtoMessage() {}

func (x *FormatBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatBatchResponse.ProtoReflect.Descriptor instead.
func (*FormatBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_formatters_rpc_formatters_formatter_proto_rawDescGZIP(), []int{1}
}

func (x *FormatBatchResponse) GetResultJson() [][]byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *FormatBatchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_pkg_formatters_rpc_formatters_formatter_proto protoreflect.FileDescriptor

const file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc = "" +
	"\n" +
	"-pkg/formatters/rpc_formatters/formatter.proto\x12\n" +
	"formatters\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19pkg/alerts/pb/alert.proto\";\n" +
	"\x12FormatBatchRequest\x12%\n" +
	"\x06alerts\x18\x01 \x03(\v2\r.alerts.AlertR\x06alerts\"N\n" +
	"\x13FormatBatchResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x03(\fR\n" +
	"resultJson\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2\x87\x02\n" +
	"\tFormatter\x12N\n" +
	"\vFormatBatch\x12\x1e.formatters.FormatBatchRequest\x1a\x1f.formatters.FormatBatchResponse\x126\n" +
	"\x04Init\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB Z\x1erpc_formatters/;rpc_formattersb\x06proto3"

var (
	file_pkg_formatters_rpc_formatters_formatter_proto_rawDescOnce sync.Once
	file_pkg_formatters_rpc_formatters_formatter_proto_rawDescData []byte
)

func file_pkg_formatters_rpc_formatters_formatter_proto_rawDescGZIP() []byte {
	file_pkg_formatters_rpc_formatters_formatter_proto_rawDescOnce.Do(func() {
		file_pkg_formatters_rpc_formatters_formatter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc), len(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc)))
	})
	return file_pkg_formatters_rpc_formatters_formatter_proto_rawDescData
}

var file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_formatters_rpc_formatters_formatter_proto_goTypes = []any{
	(*FormatBatchRequest)(nil),  // 0: formatters.FormatBatchRequest
	(*FormatBatchResponse)(nil), // 1: formatters.FormatBatchResponse
	(*pb.Alert)(nil),            // 2: alerts.Alert
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_pkg_formatters_rpc_formatters_formatter_proto_depIdxs = []int32{
	2, // 0: formatters.FormatBatchRequest.alerts:type_name -> alerts.Alert
	0, // 1: formatters.Formatter.FormatBatch:input_type -> formatters.FormatBatchRequest
	3, // 2: formatters.Formatter.Init:input_type -> google.protobuf.Empty
	3, // 3: formatters.Formatter.Shutdown:input_type -> google.protobuf.Empty
	3, // 4: formatters.Formatter.Ping:input_type -> google.protobuf.Empty
	1, // 5: formatters.Formatter.FormatBatch:output_type -> formatters.FormatBatchResponse
	3, // 6: formatters.Formatter.Init:output_type -> google.protobuf.Empty
	3, // 7: formatters.Formatter.Shutdown:output_type -> google.protobuf.Empty
	3, // 8: formatters.Formatter.Ping:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_formatters_rpc_formatters_formatter_proto_init() }
func file_pkg_formatters_rpc_formatters_formatter_proto_init() {
	if File_pkg_formatters_rpc_formatters_formatter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc), len(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_formatters_rpc_formatters_formatter_proto_goTypes,
		DependencyIndexes: file_pkg_formatters_rpc_formatters_formatter_proto_depIdxs,
		MessageInfos:      file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes,
	}.Build()
	File_pkg_formatters_rpc_formatters_formatter_proto = out.File
	file_pkg_formatters_rpc_formatters_formatter_proto_goTypes = nil
	file_pkg_formatters_rpc_formatters_formatter_proto_depIdxs = nil
}
