// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: pkg/formatters/rpc_formatters/formatter.proto

package rpc_formatters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_formatters_rpc_formatters_formatter_proto_rawDescGZIP(), []int{0}
}

type FormatBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertJson     [][]byte               `protobuf:"bytes,1,rep,name=alert_json,json=alertJson,proto3" json:"alert_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatBatchRequest) Reset() {
	*x = FormatBatchRequest{}
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatBatchRequest) ProtoMessage() {}

func (x *FormatBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatBatchRequest.ProtoReflect.Descriptor instead.
func (*FormatBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_formatters_rpc_formatters_formatter_proto_rawDescGZIP(), []int{1}
}

func (x *FormatBatchRequest) GetAlertJson() [][]byte {
	if x != nil {
		return x.AlertJson
	}
	return nil
}

type FormatBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    [][]byte               `protobuf:"bytes,1,rep,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatBatchResponse) Reset() {
	*x = FormatBatchResponse{}
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatBatchResponse) ProtoMessage() {}

func (x *FormatBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatBatchResponse.ProtoReflect.Descriptor instead.
func (*FormatBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_formatters_rpc_formatters_formatter_proto_rawDescGZIP(), []int{2}
}

func (x *FormatBatchResponse) GetResultJson() [][]byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

var File_pkg_formatters_rpc_formatters_formatter_proto protoreflect.FileDescriptor

const file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc = "" +
	"\n" +
	"-pkg/formatters/rpc_formatters/formatter.proto\x12\n" +
	"formatters\"\a\n" +
	"\x05Empty\"3\n" +
	"\x12FormatBatchRequest\x12\x1d\n" +
	"\n" +
	"alert_json\x18\x01 \x03(\fR\talertJson\"6\n" +
	"\x13FormatBatchResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x03(\fR\n" +
	"resultJson2\xe9\x01\n" +
	"\tFormatter\x12,\n" +
	"\x04Init\x12\x11.formatters.Empty\x1a\x11.formatters.Empty\x12N\n" +
	"\vFormatBatch\x12\x1e.formatters.FormatBatchRequest\x1a\x1f.formatters.FormatBatchResponse\x120\n" +
	"\bShutdown\x12\x11.formatters.Empty\x1a\x11.formatters.Empty\x12,\n" +
	"\x04Ping\x12\x11.formatters.Empty\x1a\x11.formatters.EmptyB Z\x1erpc_formatters/;rpc_formattersb\x06proto3"

var (
	file_pkg_formatters_rpc_formatters_formatter_proto_rawDescOnce sync.Once
	file_pkg_formatters_rpc_formatters_formatter_proto_rawDescData []byte
)

func file_pkg_formatters_rpc_formatters_formatter_proto_rawDescGZIP() []byte {
	file_pkg_formatters_rpc_formatters_formatter_proto_rawDescOnce.Do(func() {
		file_pkg_formatters_rpc_formatters_formatter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc), len(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc)))
	})
	return file_pkg_formatters_rpc_formatters_formatter_proto_rawDescData
}

var file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_formatters_rpc_formatters_formatter_proto_goTypes = []any{
	(*Empty)(nil),               // 0: formatters.Empty
	(*FormatBatchRequest)(nil),  // 1: formatters.FormatBatchRequest
	(*FormatBatchResponse)(nil), // 2: formatters.FormatBatchResponse
}
var file_pkg_formatters_rpc_formatters_formatter_proto_depIdxs = []int32{
	0, // 0: formatters.Formatter.Init:input_type -> formatters.Empty
	1, // 1: formatters.Formatter.FormatBatch:input_type -> formatters.FormatBatchRequest
	0, // 2: formatters.Formatter.Shutdown:input_type -> formatters.Empty
	0, // 3: formatters.Formatter.Ping:input_type -> formatters.Empty
	0, // 4: formatters.Formatter.Init:output_type -> formatters.Empty
	2, // 5: formatters.Formatter.FormatBatch:output_type -> formatters.FormatBatchResponse
	0, // 6: formatters.Formatter.Shutdown:output_type -> formatters.Empty
	0, // 7: formatters.Formatter.Ping:output_type -> formatters.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_formatters_rpc_formatters_formatter_proto_init() }
func file_pkg_formatters_rpc_formatters_formatter_proto_init() {
	if File_pkg_formatters_rpc_formatters_formatter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc), len(file_pkg_formatters_rpc_formatters_formatter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_formatters_rpc_formatters_formatter_proto_goTypes,
		DependencyIndexes: file_pkg_formatters_rpc_formatters_formatter_proto_depIdxs,
		MessageInfos:      file_pkg_formatters_rpc_formatters_formatter_proto_msgTypes,
	}.Build()
	File_pkg_formatters_rpc_formatters_formatter_proto = out.File
	file_pkg_formatters_rpc_formatters_formatter_proto_goTypes = nil
	file_pkg_formatters_rpc_formatters_formatter_proto_depIdxs = nil
}
