{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: grafana
---
{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.grafana.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.grafana.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
{{- end }}
{{- end }}
