{{- if and .Values.kapacitor.enabled .Values.kapacitor.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapacitor-data
  namespace: {{ .Values.namespace }}
  labels:
    app: kapacitor
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.kapacitor.persistence.storageClass }}
  storageClassName: {{ .Values.kapacitor.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.kapacitor.persistence.size }}
{{- end }}
