// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.1
// source: pkg/rules/rpc_rules/rule.proto

package rpc_rules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*structpb.Struct     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateBatchRequest) Reset() {
	*x = EvaluateBatchRequest{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateBatchRequest) ProtoMessage() {}

func (x *EvaluateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateBatchRequest.ProtoReflect.Descriptor instead.
func (*EvaluateBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateBatchRequest) GetEvents() []*structpb.Struct {
	if x != nil {
		return x.Events
	}
	return nil
}

// EvaluateItem carries the match outcome, optional per-event overrides, and item error.
// Empty string / nil fields mean "use YAML default".
type EvaluateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`                            // "info|low|medium|high|critical"; "" = YAML default
	Context       *structpb.Struct       `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`                              // per-event context map; nil = YAML default
	MergeByKeys   []string               `protobuf:"bytes,6,rep,name=merge_by_keys,json=mergeByKeys,proto3" json:"merge_by_keys,omitempty"` // empty = use YAML merge_by_keys
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateItem) Reset() {
	*x = EvaluateItem{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateItem) ProtoMessage() {}

func (x *EvaluateItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateItem.ProtoReflect.Descriptor instead.
func (*EvaluateItem) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateItem) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *EvaluateItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EvaluateItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EvaluateItem) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EvaluateItem) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EvaluateItem) GetMergeByKeys() []string {
	if x != nil {
		return x.MergeByKeys
	}
	return nil
}

func (x *EvaluateItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EvaluateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EvaluateItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateBatchResponse) Reset() {
	*x = EvaluateBatchResponse{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateBatchResponse) ProtoMessage() {}

func (x *EvaluateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateBatchResponse.ProtoReflect.Descriptor instead.
func (*EvaluateBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateBatchResponse) GetItems() []*EvaluateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pkg_rules_rpc_rules_rule_proto protoreflect.FileDescriptor

const file_pkg_rules_rpc_rules_rule_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/rules/rpc_rules/rule.proto\x12\x05rules\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"G\n" +
	"\x14EvaluateBatchRequest\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.google.protobuf.StructR\x06events\"\xe9\x01\n" +
	"\fEvaluateItem\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x121\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\"\n" +
	"\rmerge_by_keys\x18\x06 \x03(\tR\vmergeByKeys\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"B\n" +
	"\x15EvaluateBatchResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.rules.EvaluateItemR\x05items2\xfe\x01\n" +
	"\x04Rule\x12J\n" +
	"\rEvaluateBatch\x12\x1b.rules.EvaluateBatchRequest\x1a\x1c.rules.EvaluateBatchResponse\x126\n" +
	"\x04Init\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x16Z\x14rpc_rules/;rpc_rulesb\x06proto3"

var (
	file_pkg_rules_rpc_rules_rule_proto_rawDescOnce sync.Once
	file_pkg_rules_rpc_rules_rule_proto_rawDescData []byte
)

func file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP() []byte {
	file_pkg_rules_rpc_rules_rule_proto_rawDescOnce.Do(func() {
		file_pkg_rules_rpc_rules_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rules_rpc_rules_rule_proto_rawDesc), len(file_pkg_rules_rpc_rules_rule_proto_rawDesc)))
	})
	return file_pkg_rules_rpc_rules_rule_proto_rawDescData
}

var file_pkg_rules_rpc_rules_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_rules_rpc_rules_rule_proto_goTypes = []any{
	(*EvaluateBatchRequest)(nil),  // 0: rules.EvaluateBatchRequest
	(*EvaluateItem)(nil),          // 1: rules.EvaluateItem
	(*EvaluateBatchResponse)(nil), // 2: rules.EvaluateBatchResponse
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_pkg_rules_rpc_rules_rule_proto_depIdxs = []int32{
	3, // 0: rules.EvaluateBatchRequest.events:type_name -> google.protobuf.Struct
	3, // 1: rules.EvaluateItem.context:type_name -> google.protobuf.Struct
	1, // 2: rules.EvaluateBatchResponse.items:type_name -> rules.EvaluateItem
	0, // 3: rules.Rule.EvaluateBatch:input_type -> rules.EvaluateBatchRequest
	4, // 4: rules.Rule.Init:input_type -> google.protobuf.Empty
	4, // 5: rules.Rule.Shutdown:input_type -> google.protobuf.Empty
	4, // 6: rules.Rule.Ping:input_type -> google.protobuf.Empty
	2, // 7: rules.Rule.EvaluateBatch:output_type -> rules.EvaluateBatchResponse
	4, // 8: rules.Rule.Init:output_type -> google.protobuf.Empty
	4, // 9: rules.Rule.Shutdown:output_type -> google.protobuf.Empty
	4, // 10: rules.Rule.Ping:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_rules_rpc_rules_rule_proto_init() }
func file_pkg_rules_rpc_rules_rule_proto_init() {
	if File_pkg_rules_rpc_rules_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rules_rpc_rules_rule_proto_rawDesc), len(file_pkg_rules_rpc_rules_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rules_rpc_rules_rule_proto_goTypes,
		DependencyIndexes: file_pkg_rules_rpc_rules_rule_proto_depIdxs,
		MessageInfos:      file_pkg_rules_rpc_rules_rule_proto_msgTypes,
	}.Build()
	File_pkg_rules_rpc_rules_rule_proto = out.File
	file_pkg_rules_rpc_rules_rule_proto_goTypes = nil
	file_pkg_rules_rpc_rules_rule_proto_depIdxs = nil
}
