// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: pkg/rules/rpc_rules/rule.proto

package rpc_rules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

type EvaluateBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateBatchRequest) Reset() {
	*x = EvaluateBatchRequest{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateBatchRequest) ProtoMessage() {}

func (x *EvaluateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateBatchRequest.ProtoReflect.Descriptor instead.
func (*EvaluateBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateBatchRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// EventResult carries the match outcome and any optional per-event overrides.
// Empty string / nil fields mean "use YAML default".
type EventResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`                            // "info|low|medium|high|critical"; "" = YAML default
	ContextJson   []byte                 `protobuf:"bytes,5,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`   // JSON-encoded map[string]any; empty = nil
	MergeByKeys   []string               `protobuf:"bytes,6,rep,name=merge_by_keys,json=mergeByKeys,proto3" json:"merge_by_keys,omitempty"` // empty = use YAML merge_by_keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResult) Reset() {
	*x = EventResult{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResult) ProtoMessage() {}

func (x *EventResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResult.ProtoReflect.Descriptor instead.
func (*EventResult) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{5}
}

func (x *EventResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *EventResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventResult) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventResult) GetContextJson() []byte {
	if x != nil {
		return x.ContextJson
	}
	return nil
}

func (x *EventResult) GetMergeByKeys() []string {
	if x != nil {
		return x.MergeByKeys
	}
	return nil
}

type EvaluateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*EventResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateBatchResponse) Reset() {
	*x = EvaluateBatchResponse{}
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateBatchResponse) ProtoMessage() {}

func (x *EvaluateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rules_rpc_rules_rule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateBatchResponse.ProtoReflect.Descriptor instead.
func (*EvaluateBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateBatchResponse) GetResults() []*EventResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_pkg_rules_rpc_rules_rule_proto protoreflect.FileDescriptor

const file_pkg_rules_rpc_rules_rule_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/rules/rpc_rules/rule.proto\x12\x05rules\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\x05Event\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"5\n" +
	"\x0fEvaluateRequest\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.rules.EventR\x05event\",\n" +
	"\x10EvaluateResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\"<\n" +
	"\x14EvaluateBatchRequest\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.rules.EventR\x06events\"\xc2\x01\n" +
	"\vEventResult\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12!\n" +
	"\fcontext_json\x18\x05 \x01(\fR\vcontextJson\x12\"\n" +
	"\rmerge_by_keys\x18\x06 \x03(\tR\vmergeByKeys\"E\n" +
	"\x15EvaluateBatchResponse\x12,\n" +
	"\aresults\x18\x02 \x03(\v2\x12.rules.EventResultR\aresults2\xff\x01\n" +
	"\x04Rule\x12\"\n" +
	"\x04Init\x12\f.rules.Empty\x1a\f.rules.Empty\x12;\n" +
	"\bEvaluate\x12\x16.rules.EvaluateRequest\x1a\x17.rules.EvaluateResponse\x12J\n" +
	"\rEvaluateBatch\x12\x1b.rules.EvaluateBatchRequest\x1a\x1c.rules.EvaluateBatchResponse\x12&\n" +
	"\bShutdown\x12\f.rules.Empty\x1a\f.rules.Empty\x12\"\n" +
	"\x04Ping\x12\f.rules.Empty\x1a\f.rules.EmptyB\x16Z\x14rpc_rules/;rpc_rulesb\x06proto3"

var (
	file_pkg_rules_rpc_rules_rule_proto_rawDescOnce sync.Once
	file_pkg_rules_rpc_rules_rule_proto_rawDescData []byte
)

func file_pkg_rules_rpc_rules_rule_proto_rawDescGZIP() []byte {
	file_pkg_rules_rpc_rules_rule_proto_rawDescOnce.Do(func() {
		file_pkg_rules_rpc_rules_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rules_rpc_rules_rule_proto_rawDesc), len(file_pkg_rules_rpc_rules_rule_proto_rawDesc)))
	})
	return file_pkg_rules_rpc_rules_rule_proto_rawDescData
}

var file_pkg_rules_rpc_rules_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_rules_rpc_rules_rule_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: rules.Empty
	(*Event)(nil),                 // 1: rules.Event
	(*EvaluateRequest)(nil),       // 2: rules.EvaluateRequest
	(*EvaluateResponse)(nil),      // 3: rules.EvaluateResponse
	(*EvaluateBatchRequest)(nil),  // 4: rules.EvaluateBatchRequest
	(*EventResult)(nil),           // 5: rules.EventResult
	(*EvaluateBatchResponse)(nil), // 6: rules.EvaluateBatchResponse
}
var file_pkg_rules_rpc_rules_rule_proto_depIdxs = []int32{
	1, // 0: rules.EvaluateRequest.event:type_name -> rules.Event
	1, // 1: rules.EvaluateBatchRequest.events:type_name -> rules.Event
	5, // 2: rules.EvaluateBatchResponse.results:type_name -> rules.EventResult
	0, // 3: rules.Rule.Init:input_type -> rules.Empty
	2, // 4: rules.Rule.Evaluate:input_type -> rules.EvaluateRequest
	4, // 5: rules.Rule.EvaluateBatch:input_type -> rules.EvaluateBatchRequest
	0, // 6: rules.Rule.Shutdown:input_type -> rules.Empty
	0, // 7: rules.Rule.Ping:input_type -> rules.Empty
	0, // 8: rules.Rule.Init:output_type -> rules.Empty
	3, // 9: rules.Rule.Evaluate:output_type -> rules.EvaluateResponse
	6, // 10: rules.Rule.EvaluateBatch:output_type -> rules.EvaluateBatchResponse
	0, // 11: rules.Rule.Shutdown:output_type -> rules.Empty
	0, // 12: rules.Rule.Ping:output_type -> rules.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_rules_rpc_rules_rule_proto_init() }
func file_pkg_rules_rpc_rules_rule_proto_init() {
	if File_pkg_rules_rpc_rules_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rules_rpc_rules_rule_proto_rawDesc), len(file_pkg_rules_rpc_rules_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rules_rpc_rules_rule_proto_goTypes,
		DependencyIndexes: file_pkg_rules_rpc_rules_rule_proto_depIdxs,
		MessageInfos:      file_pkg_rules_rpc_rules_rule_proto_msgTypes,
	}.Build()
	File_pkg_rules_rpc_rules_rule_proto = out.File
	file_pkg_rules_rpc_rules_rule_proto_goTypes = nil
	file_pkg_rules_rpc_rules_rule_proto_depIdxs = nil
}
