kafka:
  brokers: blink-kafka-cluster-kafka-bootstrap.kafka:9092

# Scaler defaults for every data-plane stage.
scalerDefaults:
  minReplicas: 1
  maxReplicas: 6
  lagThreshold: "100"
  offsetResetPolicy: earliest
