// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: exec.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecMessage is written to blink-exec by event_matcher and consumed by rule_executor.
//
// RuleIDs contains the IDs of rules that passed log-type routing and matcher checks
// for this event. rule_executor evaluates only these rules, skipping the rest of
// its pool. An empty RuleIDs slice is treated as "evaluate all rules for this log type"
// (backwards-compatible for direct producers that bypass event_matcher).
type ExecMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *structpb.Struct       `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	RuleIds       []string               `protobuf:"bytes,2,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecMessage) Reset() {
	*x = ExecMessage{}
	mi := &file_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecMessage) ProtoMessage() {}

func (x *ExecMessage) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecMessage.ProtoReflect.Descriptor instead.
func (*ExecMessage) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecMessage) GetEvent() *structpb.Struct {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecMessage) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

var File_exec_proto protoreflect.FileDescriptor

const file_exec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exec.proto\x12\x04exec\x1a\x1cgoogle/protobuf/struct.proto\"W\n" +
	"\vExecMessage\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05event\x12\x19\n" +
	"\brule_ids\x18\x02 \x03(\tR\aruleIdsB\bZ\x06pb/;pbb\x06proto3"

var (
	file_exec_proto_rawDescOnce sync.Once
	file_exec_proto_rawDescData []byte
)

func file_exec_proto_rawDescGZIP() []byte {
	file_exec_proto_rawDescOnce.Do(func() {
		file_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)))
	})
	return file_exec_proto_rawDescData
}

var file_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exec_proto_goTypes = []any{
	(*ExecMessage)(nil),     // 0: exec.ExecMessage
	(*structpb.Struct)(nil), // 1: google.protobuf.Struct
}
var file_exec_proto_depIdxs = []int32{
	1, // 0: exec.ExecMessage.event:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exec_proto_init() }
func file_exec_proto_init() {
	if File_exec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exec_proto_goTypes,
		DependencyIndexes: file_exec_proto_depIdxs,
		MessageInfos:      file_exec_proto_msgTypes,
	}.Build()
	File_exec_proto = out.File
	file_exec_proto_goTypes = nil
	file_exec_proto_depIdxs = nil
}
