alert_processor_config:
  log_level: info
  log_retention_days: 14
  memory: 128
  metric_alarms:
    errors:
      enabled: true
      evaluation_periods: 1
      period_secs: 120
      threshold: 0
    throttles:
      enabled: true
      evaluation_periods: 1
      period_secs: 120
      threshold: 0
  timeout: 60
  vpc_config:
    security_group_ids: []
    subnet_ids: []