alert_merger_config:
  concurrency_limit: 1
  enable_custom_metrics: true
  log_level: info
  log_retention_days: 14
  memory: 128
  metric_alarms:
    errors:
      enabled: true
      evaluation_periods: 1
      period_secs: 120
      threshold: 0
    throttles:
      enabled: true
      evaluation_periods: 1
      period_secs: 120
      threshold: 1
  schedule_expression: rate(1 minute)
  timeout: 60
  vpc_config:
    security_group_ids: []
    subnet_ids: []