default:
  stdout:
    description: sending this to stdout for now...
    output: stdout
    debug: info
    key: value
    key2: value2
  stderr:
    description: sending this to stderr for now...
    output: stderr
    debug: info
    key: value
    key2: value2