{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: {{ .Values.namespace }}
  labels:
    app: influxdb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"

    [http]
      enabled = true
      bind-address = ":8086"
      auth-enabled = false
      log-enabled = true

    [monitor]
      store-enabled = true
      store-database = "_internal"
      store-interval = "10s"

    [[udp]]
      enabled = false

  init.sh: |
    #!/bin/sh
    set -e
    sleep 3
    influx -execute "CREATE DATABASE {{ .Values.influxdb.config.database }} WITH DURATION {{ .Values.influxdb.config.retentionDuration }} REPLICATION 1 NAME {{ .Values.influxdb.config.retentionPolicy }}" || true
    influx -execute "CREATE DATABASE _kapacitor WITH DURATION 7d REPLICATION 1" || true
{{- end }}
