{{- if .Values.influxdb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: {{ .Values.namespace }}
  labels:
    app: influxdb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      initContainers:
        - name: influxdb-init
          image: {{ .Values.influxdb.image.repository }}:{{ .Values.influxdb.image.tag }}
          imagePullPolicy: {{ .Values.influxdb.image.pullPolicy }}
          command: ["/bin/sh", "/etc/influxdb/init.sh"]
          volumeMounts:
            - name: config
              mountPath: /etc/influxdb
            - name: data
              mountPath: /var/lib/influxdb
      containers:
        - name: influxdb
          image: {{ .Values.influxdb.image.repository }}:{{ .Values.influxdb.image.tag }}
          imagePullPolicy: {{ .Values.influxdb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          env:
            - name: INFLUXDB_DB
              value: {{ .Values.influxdb.config.database }}
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "false"
          volumeMounts:
            - name: config
              mountPath: /etc/influxdb
            - name: data
              mountPath: /var/lib/influxdb
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.influxdb.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: influxdb-config
            defaultMode: 0755
        - name: data
          {{- if .Values.influxdb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: influxdb-data
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
