{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: alertmanager
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - name: http
      port: {{ .Values.alertmanager.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: alertmanager
{{- end }}
