// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: pkg/alerts/pb/alert.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleMetadata carries rule configuration in the alert wire format.
// Mirrors pkg/rules/rule.proto Metadata with additions for file_name,
// display_name, references, and risk_score.
type RuleMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled         bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Severity        string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`     // "info|low|medium|high|critical"
	Confidence      string                 `protobuf:"bytes,6,opt,name=confidence,proto3" json:"confidence,omitempty"` // "very_low|low|medium|high|very_high"
	MergeByKeys     []string               `protobuf:"bytes,7,rep,name=merge_by_keys,json=mergeByKeys,proto3" json:"merge_by_keys,omitempty"`
	MergeWindowMins uint32                 `protobuf:"varint,8,opt,name=merge_window_mins,json=mergeWindowMins,proto3" json:"merge_window_mins,omitempty"`
	ReqSubkeys      []string               `protobuf:"bytes,9,rep,name=req_subkeys,json=reqSubkeys,proto3" json:"req_subkeys,omitempty"`
	Signal          bool                   `protobuf:"varint,10,opt,name=signal,proto3" json:"signal,omitempty"`
	SignalThreshold string                 `protobuf:"bytes,11,opt,name=signal_threshold,json=signalThreshold,proto3" json:"signal_threshold,omitempty"`
	Tags            []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Dispatchers     []string               `protobuf:"bytes,13,rep,name=dispatchers,proto3" json:"dispatchers,omitempty"`
	LogTypes        []string               `protobuf:"bytes,14,rep,name=log_types,json=logTypes,proto3" json:"log_types,omitempty"`
	Matchers        []string               `protobuf:"bytes,15,rep,name=matchers,proto3" json:"matchers,omitempty"`
	Formatters      []string               `protobuf:"bytes,16,rep,name=formatters,proto3" json:"formatters,omitempty"`
	Enrichments     []string               `protobuf:"bytes,17,rep,name=enrichments,proto3" json:"enrichments,omitempty"`
	TuningRules     []string               `protobuf:"bytes,18,rep,name=tuning_rules,json=tuningRules,proto3" json:"tuning_rules,omitempty"`
	Version         string                 `protobuf:"bytes,19,opt,name=version,proto3" json:"version,omitempty"`
	FileName        string                 `protobuf:"bytes,21,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	DisplayName     string                 `protobuf:"bytes,22,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	References      []string               `protobuf:"bytes,23,rep,name=references,proto3" json:"references,omitempty"`
	RiskScore       string                 `protobuf:"bytes,24,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuleMetadata) Reset() {
	*x = RuleMetadata{}
	mi := &file_pkg_alerts_pb_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleMetadata) ProtoMessage() {}

func (x *RuleMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_alerts_pb_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleMetadata.ProtoReflect.Descriptor instead.
func (*RuleMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_alerts_pb_alert_proto_rawDescGZIP(), []int{0}
}

func (x *RuleMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleMetadata) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RuleMetadata) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RuleMetadata) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *RuleMetadata) GetMergeByKeys() []string {
	if x != nil {
		return x.MergeByKeys
	}
	return nil
}

func (x *RuleMetadata) GetMergeWindowMins() uint32 {
	if x != nil {
		return x.MergeWindowMins
	}
	return 0
}

func (x *RuleMetadata) GetReqSubkeys() []string {
	if x != nil {
		return x.ReqSubkeys
	}
	return nil
}

func (x *RuleMetadata) GetSignal() bool {
	if x != nil {
		return x.Signal
	}
	return false
}

func (x *RuleMetadata) GetSignalThreshold() string {
	if x != nil {
		return x.SignalThreshold
	}
	return ""
}

func (x *RuleMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RuleMetadata) GetDispatchers() []string {
	if x != nil {
		return x.Dispatchers
	}
	return nil
}

func (x *RuleMetadata) GetLogTypes() []string {
	if x != nil {
		return x.LogTypes
	}
	return nil
}

func (x *RuleMetadata) GetMatchers() []string {
	if x != nil {
		return x.Matchers
	}
	return nil
}

func (x *RuleMetadata) GetFormatters() []string {
	if x != nil {
		return x.Formatters
	}
	return nil
}

func (x *RuleMetadata) GetEnrichments() []string {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *RuleMetadata) GetTuningRules() []string {
	if x != nil {
		return x.TuningRules
	}
	return nil
}

func (x *RuleMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuleMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RuleMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RuleMetadata) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *RuleMetadata) GetRiskScore() string {
	if x != nil {
		return x.RiskScore
	}
	return ""
}

// Alert is the Kafka wire format for a single alert travelling through the
// tuner → enricher → formatter → dispatcher pipeline.
type Alert struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AlertId             string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Attempts            int32                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Cluster             string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	CreatedNs           int64                  `protobuf:"varint,4,opt,name=created_ns,json=createdNs,proto3" json:"created_ns,omitempty"`          // time.Time as Unix nanoseconds
	DispatchedNs        int64                  `protobuf:"varint,5,opt,name=dispatched_ns,json=dispatchedNs,proto3" json:"dispatched_ns,omitempty"` // time.Time as Unix nanoseconds (0 = not yet dispatched)
	Event               *structpb.Struct       `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`                                    // events.Event as structured protobuf
	Staged              bool                   `protobuf:"varint,7,opt,name=staged,proto3" json:"staged,omitempty"`
	OutputsSent         []string               `protobuf:"bytes,8,rep,name=outputs_sent,json=outputsSent,proto3" json:"outputs_sent,omitempty"`
	LogSource           string                 `protobuf:"bytes,9,opt,name=log_source,json=logSource,proto3" json:"log_source,omitempty"`
	LogType             string                 `protobuf:"bytes,10,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	SourceEntity        string                 `protobuf:"bytes,11,opt,name=source_entity,json=sourceEntity,proto3" json:"source_entity,omitempty"`
	SourceService       string                 `protobuf:"bytes,12,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	Confidence          string                 `protobuf:"bytes,13,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Severity            string                 `protobuf:"bytes,14,opt,name=severity,proto3" json:"severity,omitempty"`
	Rule                *RuleMetadata          `protobuf:"bytes,15,opt,name=rule,proto3" json:"rule,omitempty"`
	EnrichmentsApplied  []string               `protobuf:"bytes,16,rep,name=enrichments_applied,json=enrichmentsApplied,proto3" json:"enrichments_applied,omitempty"`
	OverrideMergeByKeys []string               `protobuf:"bytes,17,rep,name=override_merge_by_keys,json=overrideMergeByKeys,proto3" json:"override_merge_by_keys,omitempty"` // set by plugin's AlertMergeByKeys; overrides rule.merge_by_keys when non-empty
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_pkg_alerts_pb_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_alerts_pb_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_pkg_alerts_pb_alert_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Alert) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Alert) GetCreatedNs() int64 {
	if x != nil {
		return x.CreatedNs
	}
	return 0
}

func (x *Alert) GetDispatchedNs() int64 {
	if x != nil {
		return x.DispatchedNs
	}
	return 0
}

func (x *Alert) GetEvent() *structpb.Struct {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Alert) GetStaged() bool {
	if x != nil {
		return x.Staged
	}
	return false
}

func (x *Alert) GetOutputsSent() []string {
	if x != nil {
		return x.OutputsSent
	}
	return nil
}

func (x *Alert) GetLogSource() string {
	if x != nil {
		return x.LogSource
	}
	return ""
}

func (x *Alert) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *Alert) GetSourceEntity() string {
	if x != nil {
		return x.SourceEntity
	}
	return ""
}

func (x *Alert) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *Alert) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetRule() *RuleMetadata {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *Alert) GetEnrichmentsApplied() []string {
	if x != nil {
		return x.EnrichmentsApplied
	}
	return nil
}

func (x *Alert) GetOverrideMergeByKeys() []string {
	if x != nil {
		return x.OverrideMergeByKeys
	}
	return nil
}

var File_pkg_alerts_pb_alert_proto protoreflect.FileDescriptor

const file_pkg_alerts_pb_alert_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/alerts/pb/alert.proto\x12\x06alerts\x1a\x1cgoogle/protobuf/struct.proto\"\xcb\x05\n" +
	"\fRuleMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\tR\n" +
	"confidence\x12\"\n" +
	"\rmerge_by_keys\x18\a \x03(\tR\vmergeByKeys\x12*\n" +
	"\x11merge_window_mins\x18\b \x01(\rR\x0fmergeWindowMins\x12\x1f\n" +
	"\vreq_subkeys\x18\t \x03(\tR\n" +
	"reqSubkeys\x12\x16\n" +
	"\x06signal\x18\n" +
	" \x01(\bR\x06signal\x12)\n" +
	"\x10signal_threshold\x18\v \x01(\tR\x0fsignalThreshold\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12 \n" +
	"\vdispatchers\x18\r \x03(\tR\vdispatchers\x12\x1b\n" +
	"\tlog_types\x18\x0e \x03(\tR\blogTypes\x12\x1a\n" +
	"\bmatchers\x18\x0f \x03(\tR\bmatchers\x12\x1e\n" +
	"\n" +
	"formatters\x18\x10 \x03(\tR\n" +
	"formatters\x12 \n" +
	"\venrichments\x18\x11 \x03(\tR\venrichments\x12!\n" +
	"\ftuning_rules\x18\x12 \x03(\tR\vtuningRules\x12\x18\n" +
	"\aversion\x18\x13 \x01(\tR\aversion\x12\x1b\n" +
	"\tfile_name\x18\x15 \x01(\tR\bfileName\x12!\n" +
	"\fdisplay_name\x18\x16 \x01(\tR\vdisplayName\x12\x1e\n" +
	"\n" +
	"references\x18\x17 \x03(\tR\n" +
	"references\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x18 \x01(\tR\triskScore\"\xd8\x04\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x05R\battempts\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12\x1d\n" +
	"\n" +
	"created_ns\x18\x04 \x01(\x03R\tcreatedNs\x12#\n" +
	"\rdispatched_ns\x18\x05 \x01(\x03R\fdispatchedNs\x12-\n" +
	"\x05event\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05event\x12\x16\n" +
	"\x06staged\x18\a \x01(\bR\x06staged\x12!\n" +
	"\foutputs_sent\x18\b \x03(\tR\voutputsSent\x12\x1d\n" +
	"\n" +
	"log_source\x18\t \x01(\tR\tlogSource\x12\x19\n" +
	"\blog_type\x18\n" +
	" \x01(\tR\alogType\x12#\n" +
	"\rsource_entity\x18\v \x01(\tR\fsourceEntity\x12%\n" +
	"\x0esource_service\x18\f \x01(\tR\rsourceService\x12\x1e\n" +
	"\n" +
	"confidence\x18\r \x01(\tR\n" +
	"confidence\x12\x1a\n" +
	"\bseverity\x18\x0e \x01(\tR\bseverity\x12(\n" +
	"\x04rule\x18\x0f \x01(\v2\x14.alerts.RuleMetadataR\x04rule\x12/\n" +
	"\x13enrichments_applied\x18\x10 \x03(\tR\x12enrichmentsApplied\x123\n" +
	"\x16override_merge_by_keys\x18\x11 \x03(\tR\x13overrideMergeByKeysB\bZ\x06pb/;pbb\x06proto3"

var (
	file_pkg_alerts_pb_alert_proto_rawDescOnce sync.Once
	file_pkg_alerts_pb_alert_proto_rawDescData []byte
)

func file_pkg_alerts_pb_alert_proto_rawDescGZIP() []byte {
	file_pkg_alerts_pb_alert_proto_rawDescOnce.Do(func() {
		file_pkg_alerts_pb_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_alerts_pb_alert_proto_rawDesc), len(file_pkg_alerts_pb_alert_proto_rawDesc)))
	})
	return file_pkg_alerts_pb_alert_proto_rawDescData
}

var file_pkg_alerts_pb_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_alerts_pb_alert_proto_goTypes = []any{
	(*RuleMetadata)(nil),    // 0: alerts.RuleMetadata
	(*Alert)(nil),           // 1: alerts.Alert
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_pkg_alerts_pb_alert_proto_depIdxs = []int32{
	2, // 0: alerts.Alert.event:type_name -> google.protobuf.Struct
	0, // 1: alerts.Alert.rule:type_name -> alerts.RuleMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_alerts_pb_alert_proto_init() }
func file_pkg_alerts_pb_alert_proto_init() {
	if File_pkg_alerts_pb_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_alerts_pb_alert_proto_rawDesc), len(file_pkg_alerts_pb_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_alerts_pb_alert_proto_goTypes,
		DependencyIndexes: file_pkg_alerts_pb_alert_proto_depIdxs,
		MessageInfos:      file_pkg_alerts_pb_alert_proto_msgTypes,
	}.Build()
	File_pkg_alerts_pb_alert_proto = out.File
	file_pkg_alerts_pb_alert_proto_goTypes = nil
	file_pkg_alerts_pb_alert_proto_depIdxs = nil
}
