---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blink-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blink.labels" . | nindent 4 }}
data:
  KAFKA_BROKERS:         {{ .Values.kafka.brokers | quote }}
  ENVIRONMENT:           {{ .Values.environment | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: blink-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blink.labels" . | nindent 4 }}
stringData:
  PRODUCT:        {{ .Values.auth.product | quote }}
  AUTH0_AUDIENCE: {{ .Values.auth.auth0Audience | quote }}
  AUTH0_ISSUER:   {{ .Values.auth.auth0Issuer | quote }}
