// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.1
// source: snapshot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RolloutMode mirrors internal/pools.RolloutMode (iota order: blue-green, canary, shadow).
type RolloutMode int32

const (
	RolloutMode_ROLLOUT_MODE_BLUE_GREEN RolloutMode = 0
	RolloutMode_ROLLOUT_MODE_CANARY     RolloutMode = 1
	RolloutMode_ROLLOUT_MODE_SHADOW     RolloutMode = 2
)

// Enum value maps for RolloutMode.
var (
	RolloutMode_name = map[int32]string{
		0: "ROLLOUT_MODE_BLUE_GREEN",
		1: "ROLLOUT_MODE_CANARY",
		2: "ROLLOUT_MODE_SHADOW",
	}
	RolloutMode_value = map[string]int32{
		"ROLLOUT_MODE_BLUE_GREEN": 0,
		"ROLLOUT_MODE_CANARY":     1,
		"ROLLOUT_MODE_SHADOW":     2,
	}
)

func (x RolloutMode) Enum() *RolloutMode {
	p := new(RolloutMode)
	*p = x
	return p
}

func (x RolloutMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutMode) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_proto_enumTypes[0].Descriptor()
}

func (RolloutMode) Type() protoreflect.EnumType {
	return &file_snapshot_proto_enumTypes[0]
}

func (x RolloutMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutMode.Descriptor instead.
func (RolloutMode) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

// EffectiveEntry is the wire form of internal/snapshot.EffectiveEntry: the desired state for
// one logical plugin ID. The snapshot topic is per-ID keyed, so each entry is a standalone
// message (there is no aggregate Snapshot on the wire) - convert with snapshot.EntryToProto /
// EntryFromProto.
type EffectiveEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Primary       *ArtifactRef           `protobuf:"bytes,3,opt,name=primary,proto3" json:"primary,omitempty"`     // blue-green (stable) artifact; unset if none yet
	Candidate     *ArtifactRef           `protobuf:"bytes,4,opt,name=candidate,proto3" json:"candidate,omitempty"` // canary/shadow artifact; unset if BG-only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveEntry) Reset() {
	*x = EffectiveEntry{}
	mi := &file_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveEntry) ProtoMessage() {}

func (x *EffectiveEntry) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveEntry.ProtoReflect.Descriptor instead.
func (*EffectiveEntry) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *EffectiveEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EffectiveEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EffectiveEntry) GetPrimary() *ArtifactRef {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *EffectiveEntry) GetCandidate() *ArtifactRef {
	if x != nil {
		return x.Candidate
	}
	return nil
}

// ArtifactRef names one binary artifact, its rollout mode, and its config.
type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          RolloutMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=snapshot.RolloutMode" json:"mode,omitempty"`
	Spec          []byte                 `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"` // yaml-marshaled metadata for THIS artifact (lets consumers route/configure off the snapshot alone)
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"` // sha256 (hex) of the artifact binary the controller saw; empty if none present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactRef) GetMode() RolloutMode {
	if x != nil {
		return x.Mode
	}
	return RolloutMode_ROLLOUT_MODE_BLUE_GREEN
}

func (x *ArtifactRef) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ArtifactRef) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x0esnapshot.proto\x12\bsnapshot\"\xa6\x01\n" +
	"\x0eEffectiveEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12/\n" +
	"\aprimary\x18\x03 \x01(\v2\x15.snapshot.ArtifactRefR\aprimary\x123\n" +
	"\tcandidate\x18\x04 \x01(\v2\x15.snapshot.ArtifactRefR\tcandidateJ\x04\b\x05\x10\x06\"t\n" +
	"\vArtifactRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.snapshot.RolloutModeR\x04mode\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\fR\x04spec\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash*\\\n" +
	"\vRolloutMode\x12\x1b\n" +
	"\x17ROLLOUT_MODE_BLUE_GREEN\x10\x00\x12\x17\n" +
	"\x13ROLLOUT_MODE_CANARY\x10\x01\x12\x17\n" +
	"\x13ROLLOUT_MODE_SHADOW\x10\x02B\bZ\x06pb/;pbb\x06proto3"

var (
	file_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_rawDescData []byte
)

func file_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)))
	})
	return file_snapshot_proto_rawDescData
}

var file_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_snapshot_proto_goTypes = []any{
	(RolloutMode)(0),       // 0: snapshot.RolloutMode
	(*EffectiveEntry)(nil), // 1: snapshot.EffectiveEntry
	(*ArtifactRef)(nil),    // 2: snapshot.ArtifactRef
}
var file_snapshot_proto_depIdxs = []int32{
	2, // 0: snapshot.EffectiveEntry.primary:type_name -> snapshot.ArtifactRef
	2, // 1: snapshot.EffectiveEntry.candidate:type_name -> snapshot.ArtifactRef
	0, // 2: snapshot.ArtifactRef.mode:type_name -> snapshot.RolloutMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_snapshot_proto_init() }
func file_snapshot_proto_init() {
	if File_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_depIdxs,
		EnumInfos:         file_snapshot_proto_enumTypes,
		MessageInfos:      file_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto = out.File
	file_snapshot_proto_goTypes = nil
	file_snapshot_proto_depIdxs = nil
}
