// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.1
// source: pkg/tuning_rules/rpc_tuning_rules/tuning_rule.proto

package rpc_tuning_rules

import (
	pb "github.com/harishhary/blink/pkg/alerts/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TuneBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*pb.Alert            `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuneBatchRequest) Reset() {
	*x = TuneBatchRequest{}
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuneBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneBatchRequest) ProtoMessage() {}

func (x *TuneBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneBatchRequest.ProtoReflect.Descriptor instead.
func (*TuneBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP(), []int{0}
}

func (x *TuneBatchRequest) GetAlerts() []*pb.Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type TuneItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applies       bool                   `protobuf:"varint,1,opt,name=applies,proto3" json:"applies,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuneItem) Reset() {
	*x = TuneItem{}
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuneItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneItem) ProtoMessage() {}

func (x *TuneItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneItem.ProtoReflect.Descriptor instead.
func (*TuneItem) Descriptor() ([]byte, []int) {
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP(), []int{1}
}

func (x *TuneItem) GetApplies() bool {
	if x != nil {
		return x.Applies
	}
	return false
}

func (x *TuneItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TuneBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TuneItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuneBatchResponse) Reset() {
	*x = TuneBatchResponse{}
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuneBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneBatchResponse) ProtoMessage() {}

func (x *TuneBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneBatchResponse.ProtoReflect.Descriptor instead.
func (*TuneBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP(), []int{2}
}

func (x *TuneBatchResponse) GetItems() []*TuneItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto protoreflect.FileDescriptor

const file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc = "" +
	"\n" +
	"3pkg/tuning_rules/rpc_tuning_rules/tuning_rule.proto\x12\ftuning_rules\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19pkg/alerts/pb/alert.proto\"9\n" +
	"\x10TuneBatchRequest\x12%\n" +
	"\x06alerts\x18\x01 \x03(\v2\r.alerts.AlertR\x06alerts\":\n" +
	"\bTuneItem\x12\x18\n" +
	"\aapplies\x18\x01 \x01(\bR\aapplies\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\x11TuneBatchResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.tuning_rules.TuneItemR\x05items2\x86\x02\n" +
	"\n" +
	"TuningRule\x12L\n" +
	"\tTuneBatch\x12\x1e.tuning_rules.TuneBatchRequest\x1a\x1f.tuning_rules.TuneBatchResponse\x126\n" +
	"\x04Init\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB$Z\"rpc_tuning_rules/;rpc_tuning_rulesb\x06proto3"

var (
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescOnce sync.Once
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescData []byte
)

func file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP() []byte {
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescOnce.Do(func() {
		file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc), len(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc)))
	})
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescData
}

var file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_goTypes = []any{
	(*TuneBatchRequest)(nil),  // 0: tuning_rules.TuneBatchRequest
	(*TuneItem)(nil),          // 1: tuning_rules.TuneItem
	(*TuneBatchResponse)(nil), // 2: tuning_rules.TuneBatchResponse
	(*pb.Alert)(nil),          // 3: alerts.Alert
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_depIdxs = []int32{
	3, // 0: tuning_rules.TuneBatchRequest.alerts:type_name -> alerts.Alert
	1, // 1: tuning_rules.TuneBatchResponse.items:type_name -> tuning_rules.TuneItem
	0, // 2: tuning_rules.TuningRule.TuneBatch:input_type -> tuning_rules.TuneBatchRequest
	4, // 3: tuning_rules.TuningRule.Init:input_type -> google.protobuf.Empty
	4, // 4: tuning_rules.TuningRule.Shutdown:input_type -> google.protobuf.Empty
	4, // 5: tuning_rules.TuningRule.Ping:input_type -> google.protobuf.Empty
	2, // 6: tuning_rules.TuningRule.TuneBatch:output_type -> tuning_rules.TuneBatchResponse
	4, // 7: tuning_rules.TuningRule.Init:output_type -> google.protobuf.Empty
	4, // 8: tuning_rules.TuningRule.Shutdown:output_type -> google.protobuf.Empty
	4, // 9: tuning_rules.TuningRule.Ping:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_init() }
func file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_init() {
	if File_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc), len(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_goTypes,
		DependencyIndexes: file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_depIdxs,
		MessageInfos:      file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes,
	}.Build()
	File_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto = out.File
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_goTypes = nil
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_depIdxs = nil
}
