// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: pkg/tuning_rules/rpc_tuning_rules/tuning_rule.proto

package rpc_tuning_rules

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TuningRule_Init_FullMethodName      = "/tuning_rules.TuningRule/Init"
	TuningRule_TuneBatch_FullMethodName = "/tuning_rules.TuningRule/TuneBatch"
	TuningRule_Shutdown_FullMethodName  = "/tuning_rules.TuningRule/Shutdown"
	TuningRule_Ping_FullMethodName      = "/tuning_rules.TuningRule/Ping"
)

// TuningRuleClient is the client API for TuningRule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TuningRuleClient interface {
	Init(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	TuneBatch(ctx context.Context, in *TuneBatchRequest, opts ...grpc.CallOption) (*TuneBatchResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type tuningRuleClient struct {
	cc grpc.ClientConnInterface
}

func NewTuningRuleClient(cc grpc.ClientConnInterface) TuningRuleClient {
	return &tuningRuleClient{cc}
}

func (c *tuningRuleClient) Init(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TuningRule_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tuningRuleClient) TuneBatch(ctx context.Context, in *TuneBatchRequest, opts ...grpc.CallOption) (*TuneBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TuneBatchResponse)
	err := c.cc.Invoke(ctx, TuningRule_TuneBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tuningRuleClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TuningRule_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tuningRuleClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TuningRule_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TuningRuleServer is the server API for TuningRule service.
// All implementations must embed UnimplementedTuningRuleServer
// for forward compatibility.
type TuningRuleServer interface {
	Init(context.Context, *Empty) (*Empty, error)
	TuneBatch(context.Context, *TuneBatchRequest) (*TuneBatchResponse, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedTuningRuleServer()
}

// UnimplementedTuningRuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTuningRuleServer struct{}

func (UnimplementedTuningRuleServer) Init(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedTuningRuleServer) TuneBatch(context.Context, *TuneBatchRequest) (*TuneBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TuneBatch not implemented")
}
func (UnimplementedTuningRuleServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedTuningRuleServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTuningRuleServer) mustEmbedUnimplementedTuningRuleServer() {}
func (UnimplementedTuningRuleServer) testEmbeddedByValue()                    {}

// UnsafeTuningRuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TuningRuleServer will
// result in compilation errors.
type UnsafeTuningRuleServer interface {
	mustEmbedUnimplementedTuningRuleServer()
}

func RegisterTuningRuleServer(s grpc.ServiceRegistrar, srv TuningRuleServer) {
	// If the following call pancis, it indicates UnimplementedTuningRuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TuningRule_ServiceDesc, srv)
}

func _TuningRule_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TuningRuleServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TuningRule_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TuningRuleServer).Init(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TuningRule_TuneBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TuneBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TuningRuleServer).TuneBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TuningRule_TuneBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TuningRuleServer).TuneBatch(ctx, req.(*TuneBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TuningRule_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TuningRuleServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TuningRule_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TuningRuleServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TuningRule_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TuningRuleServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TuningRule_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TuningRuleServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TuningRule_ServiceDesc is the grpc.ServiceDesc for TuningRule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TuningRule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tuning_rules.TuningRule",
	HandlerType: (*TuningRuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _TuningRule_Init_Handler,
		},
		{
			MethodName: "TuneBatch",
			Handler:    _TuningRule_TuneBatch_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _TuningRule_Shutdown_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _TuningRule_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/tuning_rules/rpc_tuning_rules/tuning_rule.proto",
}
