// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: pkg/tuning_rules/rpc_tuning_rules/tuning_rule.proto

package rpc_tuning_rules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP(), []int{0}
}

type TuneBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertJson     [][]byte               `protobuf:"bytes,1,rep,name=alert_json,json=alertJson,proto3" json:"alert_json,omitempty"` // one JSON-encoded map[string]any per alert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuneBatchRequest) Reset() {
	*x = TuneBatchRequest{}
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuneBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneBatchRequest) ProtoMessage() {}

func (x *TuneBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneBatchRequest.ProtoReflect.Descriptor instead.
func (*TuneBatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP(), []int{1}
}

func (x *TuneBatchRequest) GetAlertJson() [][]byte {
	if x != nil {
		return x.AlertJson
	}
	return nil
}

type TuneBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applies       []bool                 `protobuf:"varint,1,rep,packed,name=applies,proto3" json:"applies,omitempty"` // one result per alert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuneBatchResponse) Reset() {
	*x = TuneBatchResponse{}
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuneBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneBatchResponse) ProtoMessage() {}

func (x *TuneBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneBatchResponse.ProtoReflect.Descriptor instead.
func (*TuneBatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP(), []int{2}
}

func (x *TuneBatchResponse) GetApplies() []bool {
	if x != nil {
		return x.Applies
	}
	return nil
}

var File_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto protoreflect.FileDescriptor

const file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc = "" +
	"\n" +
	"3pkg/tuning_rules/rpc_tuning_rules/tuning_rule.proto\x12\ftuning_rules\"\a\n" +
	"\x05Empty\"1\n" +
	"\x10TuneBatchRequest\x12\x1d\n" +
	"\n" +
	"alert_json\x18\x01 \x03(\fR\talertJson\"-\n" +
	"\x11TuneBatchResponse\x12\x18\n" +
	"\aapplies\x18\x01 \x03(\bR\aapplies2\xf4\x01\n" +
	"\n" +
	"TuningRule\x120\n" +
	"\x04Init\x12\x13.tuning_rules.Empty\x1a\x13.tuning_rules.Empty\x12L\n" +
	"\tTuneBatch\x12\x1e.tuning_rules.TuneBatchRequest\x1a\x1f.tuning_rules.TuneBatchResponse\x124\n" +
	"\bShutdown\x12\x13.tuning_rules.Empty\x1a\x13.tuning_rules.Empty\x120\n" +
	"\x04Ping\x12\x13.tuning_rules.Empty\x1a\x13.tuning_rules.EmptyB?Z=github.com/harishhary/blink/pkg/tuning_rules/rpc_tuning_rulesb\x06proto3"

var (
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescOnce sync.Once
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescData []byte
)

func file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescGZIP() []byte {
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescOnce.Do(func() {
		file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc), len(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc)))
	})
	return file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDescData
}

var file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_goTypes = []any{
	(*Empty)(nil),             // 0: tuning_rules.Empty
	(*TuneBatchRequest)(nil),  // 1: tuning_rules.TuneBatchRequest
	(*TuneBatchResponse)(nil), // 2: tuning_rules.TuneBatchResponse
}
var file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_depIdxs = []int32{
	0, // 0: tuning_rules.TuningRule.Init:input_type -> tuning_rules.Empty
	1, // 1: tuning_rules.TuningRule.TuneBatch:input_type -> tuning_rules.TuneBatchRequest
	0, // 2: tuning_rules.TuningRule.Shutdown:input_type -> tuning_rules.Empty
	0, // 3: tuning_rules.TuningRule.Ping:input_type -> tuning_rules.Empty
	0, // 4: tuning_rules.TuningRule.Init:output_type -> tuning_rules.Empty
	2, // 5: tuning_rules.TuningRule.TuneBatch:output_type -> tuning_rules.TuneBatchResponse
	0, // 6: tuning_rules.TuningRule.Shutdown:output_type -> tuning_rules.Empty
	0, // 7: tuning_rules.TuningRule.Ping:output_type -> tuning_rules.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_init() }
func file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_init() {
	if File_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc), len(file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_goTypes,
		DependencyIndexes: file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_depIdxs,
		MessageInfos:      file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_msgTypes,
	}.Build()
	File_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto = out.File
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_goTypes = nil
	file_pkg_tuning_rules_rpc_tuning_rules_tuning_rule_proto_depIdxs = nil
}
