name: "go static analysis"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: ["1.26.5"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - run: go test ./...
      - run: go vet ./...
      - uses: dominikh/staticcheck-action@v1.4.1
        with:
          version: "2026.1"
          install-go: false
          cache-key: ${{ matrix.os }}-${{ matrix.go }}
